import React, { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { CalendarDays, CheckCircle2, Clock3, Download, FileText, Search, Send, Trash2, Upload, UserRound, Save, MessageSquareText } from 'lucide-react';

const assignmentsSeed=[
 {id:1,course:'Java Programming',title:'Adaptive Quiz — OOP',deadline:'10.09.2026 23:59',status:'IN PROGRESS',score:null},
 {id:2,course:'Database Systems',title:'Lab 2 — SQL JOIN',deadline:'12.09.2026 23:59',status:'NOT STARTED',score:null},
 {id:3,course:'HCI',title:'Usability Analysis',deadline:'14.09.2026 23:59',status:'SUBMITTED',score:88},
];

export function StudyPlan(){return <Page title="Оқу жоспары" subtitle="Семестр бойынша пәндер, кредиттер және оқу прогресі."><Table headers={['Пән','Код','Кредит','Статус']} rows={[[<Link to="/courses/1">Java Programming</Link>,'JAVA101','5','Оқылуда'],['Database Systems','DB202','5','Оқылуда'],['Human-Computer Interaction','HCI301','4','Оқылуда'],['Probability and Statistics','STAT210','5','Оқылуда'],['English','ENG201','3','Оқылуда']]}/></Page>}

export function Schedule(){const [day,setDay]=useState('Дүйсенбі'); const schedule={Дүйсенбі:[['10:00','HCI','304','Сейтқұлов А.Е.'],['12:00','Database Systems','318','Ибрайимова Г.К.'],['14:00','Probability and Statistics','201','Тулебаев М.С.']],Сейсенбі:[['09:00','Java Programming','220','A. Lecturer'],['13:00','English','401','Johnson P.']],Сәрсенбі:[['10:00','Database Lab','Lab 2','Ибрайимова Г.К.']]}; return <Page title="Оқу кестесі" subtitle="Апталық сабақ кестесі және аудиториялар."><div className="segmented">{Object.keys(schedule).map(d=><button className={day===d?'active':''} onClick={()=>setDay(d)} key={d}>{d}</button>)}</div><div className="list-card">{(schedule[day]||[]).map((x,i)=><div className="schedule-line" key={i}><time>{x[0]}</time><CalendarDays/><div><strong>{x[1]}</strong><small>Аудитория: {x[2]} · {x[3]}</small></div></div>)}</div></Page>}

export function Assignments(){const [items,setItems]=useState(()=>JSON.parse(localStorage.getItem('assignments')||'null')||assignmentsSeed); function toggle(id){const n=items.map(x=>x.id===id?{...x,status:x.status==='SUBMITTED'?'IN PROGRESS':'SUBMITTED'}:x);setItems(n);localStorage.setItem('assignments',JSON.stringify(n))} return <Page title="Тапсырмалар" subtitle="Deadline, status және тапсырманы тапсыру әрекеттері."><div className="cards-list">{items.map(a=><article className="assignment-card" key={a.id}><div><span className="pill">{a.course}</span><h3>{a.title}</h3><p><Clock3 size={15}/> {a.deadline}</p></div><div><span className={`status-label ${a.status.replace(' ','-').toLowerCase()}`}>{a.status}</span>{a.score&&<b>{a.score}%</b>}<button className="small-primary" onClick={()=>toggle(a.id)}>{a.status==='SUBMITTED'?<><CheckCircle2/>Қайтару</>:<><Upload/>Тапсыру</>}</button></div></article>)}</div></Page>}

export function Testing(){return <Page title="Тестілеу" subtitle="Diagnostic және adaptive quiz бөлімдері."><div className="feature-grid"><Feature title="Diagnostic Test" text="Бастапқы деңгейді анықтайды." action={<Link className="primary" to="/diagnostic/1">Бастау</Link>}/><Feature title="Adaptive Quiz" text="Нәтижеге қарай Easy / Medium / Hard өзгереді." action={<Link className="primary" to="/courses/1">Тақырып таңдау</Link>}/><Feature title="AI Practice" text="AI әлсіз тақырып бойынша сұрақ ұсынады." action={<Link className="secondary" to="/ai">AI Tutor</Link>}/></div></Page>}

export function Grades(){return <Page title="Бағалар" subtitle="Ағымдағы үлгерім және пәндер бойынша қорытынды."><Table headers={['Пән','Quiz','Assignment','Midterm','Жалпы']} rows={[[<Link to="/courses/1">Java Programming</Link>,'78%','88%','82%','82%'],['Database Systems','74%','90%','70%','78%'],['HCI','86%','92%','84%','87%'],['Statistics','66%','75%','64%','68%'],['English','92%','88%','91%','90%']]}/></Page>}

export function AcademicCalendar(){return <Page title="Академиялық күнтізбе" subtitle="2026 күзгі семестрдің негізгі күндері."><div className="calendar-events"><Event date="01 Қыр" title="Семестр басталуы"/><Event date="12–17 Қаз" title="Midterm Week"/><Event date="02–07 Жел" title="Final Projects"/><Event date="15–25 Жел" title="Final Exams"/></div></Page>}
export function Journal(){return <Page title="Журнал" subtitle="Қатысу және сабақ белсенділігі."><Table headers={['Күні','Пән','Қатысу','Белсенділік']} rows={[["09.09.2026",'Java Programming','Қатысты','5/5'],['08.09.2026','HCI','Қатысты','4/5'],['07.09.2026','Database Systems','Қатысты','5/5'],['06.09.2026','Statistics','Себепті','—']]}/></Page>}

export function Applications(){const [text,setText]=useState(''); const [sent,setSent]=useState(false); return <Page title="Өтініштер" subtitle="Академиялық сұранысты онлайн жіберу."><div className="form-card"><label>Өтініш түрі<select><option>Анықтама алу</option><option>Пәнге тіркелу</option><option>Академиялық демалыс</option><option>Басқа</option></select></label><label>Мәтін<textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Өтініш мәтінін жазыңыз..."/></label><button className="primary inline" onClick={()=>text.trim()&&setSent(true)}><Send size={17}/>Жіберу</button>{sent&&<div className="success-note">Өтініш қабылданды. №REQ-2026-104</div>}</div></Page>}

export function Materials(){const docs=[['Java Variables.pdf','JAVA101','1.2 MB'],['OOP Cheat Sheet.pdf','JAVA101','820 KB'],['SQL JOIN Practice.pdf','DB202','640 KB'],['HCI Usability Heuristics.pdf','HCI301','980 KB']]; return <Page title="Оқу материалдары" subtitle="Пәндер бойынша файлдар мен оқу ресурстары."><div className="cards-list">{docs.map((d,i)=><article className="material-card" key={i}><FileText/><div><strong>{d[0]}</strong><small>{d[1]} · {d[2]}</small></div><button onClick={()=>alert(`${d[0]} — demo download`)}><Download/></button></article>)}</div></Page>}

export function Transcript(){return <Page title="Транскрипт" subtitle="Академиялық көрсеткіштер мен GPA."><div className="transcript-summary"><div><small>GPA</small><strong>3.42</strong></div><div><small>Жиналған кредит</small><strong>74</strong></div><div><small>Academic status</small><strong>Good Standing</strong></div></div><Table headers={['Пән','Кредит','Баға','GPA']} rows={[["Programming I",5,'A-','3.67'],['Database Fundamentals',5,'B+','3.33'],['Discrete Mathematics',5,'B','3.0'],['English I',3,'A','4.0']]}/></Page>}

export function Appeals(){const [submitted,setSubmitted]=useState(false);return <Page title="Апелляциялар" subtitle="Баға немесе тест нәтижесіне апелляция беру."><div className="form-card"><label>Пән<select><option>Java Programming</option><option>Database Systems</option></select></label><label>Себеп<textarea placeholder="Апелляция себебін жазыңыз..."/></label><button className="primary" onClick={()=>setSubmitted(true)}>Апелляция жіберу</button>{submitted&&<div className="success-note">Апелляция тіркелді.</div>}</div></Page>}

export function Messages(){const [messages,setMessages]=useState([{id:1,from:'A. Lecturer',text:'Java бойынша жаңа материал жүктедім.',time:'14:20'},{id:2,from:'Academic Office',text:'Семестр күнтізбесі жаңартылды.',time:'Кеше'}]);const [draft,setDraft]=useState('');function send(){if(!draft.trim())return;setMessages([...messages,{id:Date.now(),from:'Сіз',text:draft,time:'Қазір'}]);setDraft('')}return <Page title="Хабарламалар" subtitle="Оқытушылармен және академиялық бөліммен байланыс."><div className="messages-page"><div className="message-thread">{messages.map(m=><div className="chat-item" key={m.id}><div className="message-avatar">{m.from[0]}</div><div><strong>{m.from}</strong><p>{m.text}</p><small>{m.time}</small></div></div>)}</div><div className="message-compose"><input value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Хабарлама жазыңыз..." onKeyDown={e=>e.key==='Enter'&&send()}/><button onClick={send}><Send/></button></div></div></Page>}

export function Profile(){const [name,setName]=useState(()=>JSON.parse(localStorage.getItem('user')||'{}').name||'Demo Student');const [saved,setSaved]=useState(false);return <Page title="Жеке кабинет" subtitle="Профиль және студент ақпараты."><div className="profile-card"><div className="big-avatar"><UserRound/></div><div className="profile-form"><label>Аты-жөні<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Email<input value="student@demo.kz" readOnly/></label><label>Мамандық<input value="Information Systems" readOnly/></label><label>Рөл<input value="STUDENT" readOnly/></label><button className="primary inline" onClick={()=>setSaved(true)}><Save size={17}/>Сақтау</button>{saved&&<span className="saved-text">Сақталды ✓</span>}</div></div></Page>}

export function SettingsPage(){const [email,setEmail]=useState(true);const [ai,setAi]=useState(true);const [compact,setCompact]=useState(false);return <Page title="Параметрлер" subtitle="Хабарландырулар және интерфейс параметрлері."><div className="settings-card"><Toggle label="Email хабарландырулары" checked={email} set={setEmail}/><Toggle label="AI Recommendation" checked={ai} set={setAi}/><Toggle label="Компакт интерфейс" checked={compact} set={setCompact}/><button className="primary" onClick={()=>localStorage.setItem('settings',JSON.stringify({email,ai,compact}))}>Сақтау</button></div></Page>}

export function Support(){const [q,setQ]=useState('');return <Page title="Қолдау қызметі" subtitle="Техникалық немесе оқу мәселесі бойынша сұрақ жіберіңіз."><div className="form-card"><label>Сұрақ<textarea value={q} onChange={e=>setQ(e.target.value)} placeholder="Мәселені сипаттаңыз..."/></label><button className="primary inline" onClick={()=>q&&alert('Support ticket created: SUP-2026-31')}><MessageSquareText size={17}/>Ticket ашу</button></div></Page>}

function Page({title,subtitle,children}){return <><header className="portal-page-head"><div><h1>{title}</h1><p>{subtitle}</p></div></header>{children}</>}
function Feature({title,text,action}){return <article className="feature-card"><h3>{title}</h3><p>{text}</p>{action}</article>}
function Event({date,title}){return <div className="calendar-event"><b>{date}</b><span>{title}</span></div>}
function Toggle({label,checked,set}){return <label className="toggle-row"><span>{label}</span><input type="checkbox" checked={checked} onChange={e=>set(e.target.checked)}/><i/></label>}
function Table({headers,rows}){return <div className="table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div>}
